### ISSUE TITLE
Mac OS X "malloc.h not found"

### ISSUE THREAD

**Issue by Dog** [HackerN64/HackerOoT#83] opened 2024-02-28 17:56 UTC
When doing `gmake setup` I am getting an `src/doltool.c:3:10: fatal error: 'malloc.h' file not found`.

I was able to resolve the issue by doing this:

```
vi tools/gzinject/src/doltool.c
```

and changing the import to:

```
#if defined(__MACH__)
  #include <stdlib.h>
#else 
  #include <malloc.h>
```

Not entirely sure if this is an upstream issue, but thought I'd put it here in case anyone had an issue with it.

**Comment by Yanis42** [comment] 2024-02-28 18:37
hi!

so, I don't own any system with macOS on it so I can't try this myself unfortunately, is there anything different between gmake and "classic" make? also if that's an issue related to gzinject you should probably port this issue to gzinject's repo (https://github.com/krimtonz/gzinject), apparently there's known issues with macOS

either way I'll think about how to handle this issue, thanks for the report (also feel free to join the discord server to make talking about it easier: https://discord.gg/brETAakcXr)

**Comment by Yanis42** [comment] 2024-04-10 23:24
gonna close this issue as it's not directly caused by this HackerOoT and the fix was mentioned above

**Closed by Yanis42** 2024-04-10 23:24 UTC

**Comment by Yanis42** [comment] 2024-04-25 01:36
the recent gamecube support I'm working on fixed this issue as I need to get a modified version of gzinject, and it was done on mac (see #102 ) so this will probably be fixed in the near future
